### ISSUE TITLE
userIdentifier causes infinite render loop

### ISSUE THREAD

**Issue by pr0da** [marvelapp/react-ab-test#24]
<h1>Table of Contents</h1>

- [Expected Behavior](#expected-behavior)
- [Current Behavior](#current-behavior)
- [Possible Solution](#possible-solution)
- [Steps to Reproduce (for bugs)](#steps-to-reproduce-for-bugs)
- [Context](#context)
- [Your Environment](#your-environment)

## Expected Behavior

The `userIdentifier` prop should not cause infinite render loop, when used on the client side.

## Current Behavior

When the `userIdentifier` prop is present, it causes infinite render loop.

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/white-firefly-o3bqr

Trigger a re-render with the button.

## Your Environment

* Version used: 3.0.0-beta.0
* Browser Name and version: 
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by j-5-s** [comment]
im also seeing this issue. I made [a pr](https://github.com/marvelapp/react-ab-test/pull/25) that should address it.

**Comment by moretti** [comment]
This should be fixed in `v3.0.1`.

**Comment by AlexanderChiclana** [comment]
> This should be fixed in `v3.0.1`.

Still having this issue, happens when trying to switch between variants locally if there is any userIdentifier set. 

Tried with 3.0.1 and 3.1.0
